name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  rspec-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Check for cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        upload-chunk-size: 3000000
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --with=test

    # TODO: Not necessary to setup database?
    # ans: Rails sets up development.sqlite and test.sqlite automatically when we start the app.

    - name: Run unit tests
      env:
        RAILS_ENV: test
      run: >-
        bundle exec rspec --tag ~type:feature
